### ISSUE TITLE
No longer works for cucumber >= 2.2

### ISSUE THREAD

**Issue by kratob** [makandra/cucumber_priority#4]

**Comment by triskweline** [comment]
Is this a problem with Cucumber 2.2 in particular? Since we have [tests](https://github.com/makandra/cucumber_priority/tree/master/gemfiles) for Cucumber 2.4 and 3.0 beta.

I would prefer to support only the latest minor version for each major version.

**Comment by kratob** [comment]
It failed for us on 2.2, 2.3 and 2.4. Will look into it.

**Comment by foobear** [comment]
Looked into this, and leaving this here as a note for later, when we have time to fix it. :)

The culprit on Cucumber 2.2+ is `Cucumber::StepMatchSearch::AssertUnambiguousMatch#call` which raises the "usual" error if there are multiple results.

Cucumber Priority currently patches `Cucumber::RunTime::SupportCode#step_matches` and `#step_match` which still exists in 2.2+ but is actually not called (parsing the scenario fails already).
The `step_matches_without_priority` method that Cucumber Priority adds to `SupportCode` should be moved into `CucumberPriority::Util` so it can be called from `SupportCode` *and* for `AssertUnambiguousMatch`. The latter needs to be patched like this:
```
def call_with_priority(*args)
  call_without_priority(*args)
rescue Ambiguous => e
  CucumberPriority::Util.resolve_ambiguity_through_priority(e).first
end

CucumberPriority::Util.alias_chain self, :call, :priority
```

Also, tests currently won't uncover the issue for recent cucumbers because their approach does not match a real-world test. It seems tests need to be rewritten completely, maybe simply call the `cucumber` binary to have it run tests, and use `Open3` to capture results for inspection.

An alternative *might* be mimic Cucumber behavior by asking it to compile the step. It could look something like this (not working!):
```
def compile_step(step)
  document = Cucumber::Core::Gherkin::Document.new('test.feature', <<-FEATURE)
    Feature:
      Scenario:
        Given #{step}
  FEATURE

  report = Cucumber::Formatter::Fanout.new([])
  test_runner = Cucumber::Core::Test::Runner.new(report)
  filters = [Cucumber::Filters::ActivateSteps.new]

  @runtime.compile([document], test_runner, filters)
end
```
However, I believe this approach would make specs more cumbersome and not really much more helpful.

**Comment by triskweline** [comment]
Thanks for looking into this @foobear .

I strongly recommend just shelling out to the `cucumber` binary and accept the performance hit this brings with it. Classes like `Cucumber::Core::Gherkin::Document` are all internal API, the use of which brought us into this situation in the first place.
